[package]
name = "pack-pdf"
version = "0.1.0"
authors = ["Jussi Niinikoski <jussi.niinikoski@perjantai.fi>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.45", features = ["serde-serialize"]  }
js-sys = "0.3.22"
serde = { version = "1.0.91", features = ["derive"] }
serde_derive = "1.0.91"
deflate = "0.7.19"
base64 = "0.10.1"
lazy_static = "1.3.0"

[dependencies.web-sys]
version = "0.3.22"
features = [
  'Window',
]
